# REV 1.4
# 1.0 - initial release
# 1.1 - updated container image address to point to internal cache harbor
# 1.2 - implementing REV version(s) for quick version validation/comparison
# 1.3 - implementing reusable workflow
# 1.4 - implementing auto tagging feature and command flag support (https://github.com/intel-innersource/frameworks.actions.semgrep-auto-tag-scan)

# Name of this GitHub Actions workflow.
name: ServiceNow Cloud Semgrep SAST

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

  # Scan mainline branches and report all findings:
  # Ensure you have the correct branch/es for your project
  # Recommend only setting the default branch on push, or branches you push to frequently
  push:
    branches: ["intel-hr"]

  # Schedule the CI job (this method uses cron syntax):
  #schedule:
    #- cron: '0 0 1 * *' # Sets Semgrep to scan on the 1st of every month at 12:00 AM UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  Call-Workflow:
    uses: intel-innersource/frameworks.actions.semgrep-static-code-scan/.github/workflows/semgrep.yml@1.4.0
    with:
    # Please insert the runner group for your project
    # Example: runner-group: 'innersource.prod.amr.dind'
      runner-group: 'innersource.prod.amr.dind'
    # Please insert the IAPM ID of the application here
    # If the ID not entered the auto-tagging feature will not work
      iapm-id: '35521'
    # Please indicate if this should be calculated for ASPN scoring entering true
    # If set to true, the default branch will be tagged as prod and all other branches will be tagged as dev
      prod-scan: ''
    # Enter any option command flags for debugging the scan or obtaining additional details
    # Example: '--verbose --max-target-bytes=500000'
      semgrep-flags: ''
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}